// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.
import { create, fromBinary, toBinary, fromJson, toJson, createRegistry } from '@bufbuild/protobuf'
import type { DescMessage } from '@bufbuild/protobuf'
import type { MessageInitShape } from '@bufbuild/protobuf'
import type { Transport, MethodSpec, Headers, HandlerContext, ServerStream } from '../../../protocol.js'
import { frame, contentKindHeader } from '../../../protocol.js'
import type { ContentKind } from '../../../protocol.js'
import type { ServiceHandlers } from '../../../protocol.js'

/** Per-call options: cancellation, extra metadata, and unary trailer hook. */
export interface CallOptions { signal?: AbortSignal; metadata?: Headers; onTrailer?: (trailers: Headers) => void; kind?: ContentKind }
import { file_easyrpc_kitchensink_v1_kitchen } from './kitchen_pb.js'

/** JSON type registry (required to encode google.protobuf.Any to JSON). */
const jsonRegistry = createRegistry(file_easyrpc_kitchensink_v1_kitchen)
const toJsonOpts = { registry: jsonRegistry }
import { GetThingRequest, GetThingResponse, ListThingsRequest, ListThingsResponse, WatchThingsRequest, WatchThingsResponse, NoRouteRequest, NoRouteResponse, GetThingRequestSchema, GetThingResponseSchema, ListThingsRequestSchema, ListThingsResponseSchema, WatchThingsRequestSchema, WatchThingsResponseSchema, NoRouteRequestSchema, NoRouteResponseSchema } from './kitchen_pb.js'

export const methodSpecs: MethodSpec[] = [
  { service: "easyrpc.kitchensink.v1.ThingService", name: "GetThing", path: "/easyrpc.kitchensink.v1.ThingService/GetThing", clientStream: false, serverStream: false },
  { service: "easyrpc.kitchensink.v1.ThingService", name: "ListThings", path: "/easyrpc.kitchensink.v1.ThingService/ListThings", clientStream: false, serverStream: false },
  { service: "easyrpc.kitchensink.v1.ThingService", name: "WatchThings", path: "/easyrpc.kitchensink.v1.ThingService/WatchThings", clientStream: false, serverStream: true },
  { service: "easyrpc.kitchensink.v1.ThingService", name: "NoRoute", path: "/easyrpc.kitchensink.v1.ThingService/NoRoute", clientStream: false, serverStream: false },
  { service: "easyrpc.kitchensink.v1.AdminThingService", name: "Reset", path: "/easyrpc.kitchensink.v1.AdminThingService/Reset", clientStream: false, serverStream: false },
]

export interface ThingServiceClient {
  getThing(req: MessageInitShape<typeof GetThingRequestSchema>, options?: CallOptions): Promise<GetThingResponse>
  listThings(req: MessageInitShape<typeof ListThingsRequestSchema>, options?: CallOptions): Promise<ListThingsResponse>
  watchThings(req: MessageInitShape<typeof WatchThingsRequestSchema>, options?: CallOptions): Promise<ServerStream<WatchThingsResponse>>
  noRoute(req: MessageInitShape<typeof NoRouteRequestSchema>, options?: CallOptions): Promise<NoRouteResponse>
}
export function createThingServiceClient(transport: Transport): ThingServiceClient {
  return {
    async getThing(reqInit, options = {}) {
      const req = create(GetThingRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(GetThingRequestSchema, req, toJsonOpts))) : toBinary(GetThingRequestSchema, req)
      const body = encode()
      const call = { url: "/easyrpc.kitchensink.v1.ThingService/GetThing", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(GetThingResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(GetThingResponseSchema, res.body)
    },
    async listThings(reqInit, options = {}) {
      const req = create(ListThingsRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ListThingsRequestSchema, req, toJsonOpts))) : toBinary(ListThingsRequestSchema, req)
      const body = encode()
      const call = { url: "/easyrpc.kitchensink.v1.ThingService/ListThings", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(ListThingsResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(ListThingsResponseSchema, res.body)
    },
    async watchThings(reqInit, options = {}) {
      const req = create(WatchThingsRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(true, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(WatchThingsRequestSchema, req, toJsonOpts))) : toBinary(WatchThingsRequestSchema, req)
      const body = frame(encode())
      const call = { url: "/easyrpc.kitchensink.v1.ThingService/WatchThings", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const s = await transport.openStream(call)
      const decode = (chunk: Uint8Array) => kind === 'json' ? fromJson(WatchThingsResponseSchema, JSON.parse(new TextDecoder().decode(chunk))) : fromBinary(WatchThingsResponseSchema, chunk)
      const out: ServerStream<WatchThingsResponse> = {
        async *[Symbol.asyncIterator]() { for await (const chunk of s) yield decode(chunk) },
        trailers: () => s.trailers(),
        cancel: () => s.cancel(),
      }
      return out
    },
    async noRoute(reqInit, options = {}) {
      const req = create(NoRouteRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(NoRouteRequestSchema, req, toJsonOpts))) : toBinary(NoRouteRequestSchema, req)
      const body = encode()
      const call = { url: "/easyrpc.kitchensink.v1.ThingService/NoRoute", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(NoRouteResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(NoRouteResponseSchema, res.body)
    },
  }
}

export interface ThingServiceServiceImpl {
  getThing(req: GetThingRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof GetThingResponseSchema>>
  listThings(req: ListThingsRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof ListThingsResponseSchema>>
  watchThings(req: WatchThingsRequest, ctx: HandlerContext): AsyncIterable<MessageInitShape<typeof WatchThingsResponseSchema>>
  noRoute(req: NoRouteRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof NoRouteResponseSchema>>
}

export function ThingServiceHandlers(impl: ThingServiceServiceImpl): ServiceHandlers {
  const unary: ServiceHandlers['unary'] = {}
  const stream: ServiceHandlers['stream'] = {}
  unary["GetThing"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(GetThingRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(GetThingRequestSchema, input)
    const v = create(GetThingResponseSchema, await impl.getThing(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(GetThingResponseSchema, v, toJsonOpts))) : toBinary(GetThingResponseSchema, v)
  }
  unary["ListThings"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(ListThingsRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(ListThingsRequestSchema, input)
    const v = create(ListThingsResponseSchema, await impl.listThings(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ListThingsResponseSchema, v, toJsonOpts))) : toBinary(ListThingsResponseSchema, v)
  }
  stream["WatchThings"] = async (input, ctx, emit) => {
    const req = ctx.kind === 'json' ? fromJson(WatchThingsRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(WatchThingsRequestSchema, input)
    const enc = (v: MessageInitShape<typeof WatchThingsResponseSchema>) => { const msg = create(WatchThingsResponseSchema, v); return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(WatchThingsResponseSchema, msg, toJsonOpts))) : toBinary(WatchThingsResponseSchema, msg) }
    for await (const v of await impl.watchThings(req, ctx)) { await emit(enc(v), false) }
    await emit(new Uint8Array(0), true)
  }
  unary["NoRoute"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(NoRouteRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(NoRouteRequestSchema, input)
    const v = create(NoRouteResponseSchema, await impl.noRoute(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(NoRouteResponseSchema, v, toJsonOpts))) : toBinary(NoRouteResponseSchema, v)
  }
  return { unary, stream }
}

export interface AdminThingServiceClient {
  reset(req: MessageInitShape<typeof NoRouteRequestSchema>, options?: CallOptions): Promise<NoRouteResponse>
}
export function createAdminThingServiceClient(transport: Transport): AdminThingServiceClient {
  return {
    async reset(reqInit, options = {}) {
      const req = create(NoRouteRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(NoRouteRequestSchema, req, toJsonOpts))) : toBinary(NoRouteRequestSchema, req)
      const body = encode()
      const call = { url: "/easyrpc.kitchensink.v1.AdminThingService/Reset", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(NoRouteResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(NoRouteResponseSchema, res.body)
    },
  }
}

export interface AdminThingServiceServiceImpl {
  reset(req: NoRouteRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof NoRouteResponseSchema>>
}

export function AdminThingServiceHandlers(impl: AdminThingServiceServiceImpl): ServiceHandlers {
  const unary: ServiceHandlers['unary'] = {}
  const stream: ServiceHandlers['stream'] = {}
  unary["Reset"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(NoRouteRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(NoRouteRequestSchema, input)
    const v = create(NoRouteResponseSchema, await impl.reset(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(NoRouteResponseSchema, v, toJsonOpts))) : toBinary(NoRouteResponseSchema, v)
  }
  return { unary, stream }
}

