// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.
package kitchensinkv1

import (
	easyrpc "github.com/easy-utils/easy-rpc-go"
	"context"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

func ThingService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "easyrpc.kitchensink.v1.ThingService", Name: "GetThing", Path: "/easyrpc.kitchensink.v1.ThingService/GetThing", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.kitchensink.v1.ThingService", Name: "ListThings", Path: "/easyrpc.kitchensink.v1.ThingService/ListThings", ClientStream: false, ServerStream: false},
		{Service: "easyrpc.kitchensink.v1.ThingService", Name: "WatchThings", Path: "/easyrpc.kitchensink.v1.ThingService/WatchThings", ClientStream: false, ServerStream: true},
		{Service: "easyrpc.kitchensink.v1.ThingService", Name: "NoRoute", Path: "/easyrpc.kitchensink.v1.ThingService/NoRoute", ClientStream: false, ServerStream: false},
	}
}

type ThingServiceClient struct { rt easyrpc.Transport }
func NewThingServiceClient(rt easyrpc.Transport) *ThingServiceClient { return &ThingServiceClient{rt: rt} }

func (c *ThingServiceClient) GetThing(ctx context.Context, in *GetThingRequest, opts ...easyrpc.CallOption) (*GetThingResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.kitchensink.v1.ThingService/GetThing", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &GetThingResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *ThingServiceClient) ListThings(ctx context.Context, in *ListThingsRequest, opts ...easyrpc.CallOption) (*ListThingsResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.kitchensink.v1.ThingService/ListThings", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &ListThingsResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

func (c *ThingServiceClient) WatchThings(ctx context.Context, in *WatchThingsRequest, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	return c.rt.OpenStream(ctx, easyrpc.Request{URL: "/easyrpc.kitchensink.v1.ThingService/WatchThings", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(true, kind)}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)})
}

func (c *ThingServiceClient) NoRoute(ctx context.Context, in *NoRouteRequest, opts ...easyrpc.CallOption) (*NoRouteResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.kitchensink.v1.ThingService/NoRoute", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &NoRouteResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

type ThingServiceService interface {
	GetThing(ctx context.Context, in *GetThingRequest) (*GetThingResponse, error)
	ListThings(ctx context.Context, in *ListThingsRequest) (*ListThingsResponse, error)
	WatchThings(ctx context.Context, in *WatchThingsRequest, emit func(*WatchThingsResponse) error) error
	NoRoute(ctx context.Context, in *NoRouteRequest) (*NoRouteResponse, error)
}

func RegisterThingServiceService(impl ThingServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["GetThing"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &GetThingRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.GetThing(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Unary["ListThings"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &ListThingsRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.ListThings(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	reg.Stream["WatchThings"] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {
		in := &WatchThingsRequest{}
		if err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		return impl.WatchThings(ctx, in, func(out *WatchThingsResponse) error { return emit(encodeMsg(out, kind), false) })
	}
	reg.Unary["NoRoute"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &NoRouteRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.NoRoute(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	return reg
}

func AdminThingService_Methods() []easyrpc.MethodSpec {
	return []easyrpc.MethodSpec{
		{Service: "easyrpc.kitchensink.v1.AdminThingService", Name: "Reset", Path: "/easyrpc.kitchensink.v1.AdminThingService/Reset", ClientStream: false, ServerStream: false},
	}
}

type AdminThingServiceClient struct { rt easyrpc.Transport }
func NewAdminThingServiceClient(rt easyrpc.Transport) *AdminThingServiceClient { return &AdminThingServiceClient{rt: rt} }

func (c *AdminThingServiceClient) Reset(ctx context.Context, in *NoRouteRequest, opts ...easyrpc.CallOption) (*NoRouteResponse, error) {
	kind := easyrpc.KindProto
	for _, o := range opts { o(&kind) }
	resp, err := c.rt.Send(ctx, easyrpc.Request{URL: "/easyrpc.kitchensink.v1.AdminThingService/Reset", Headers: easyrpc.Headers{"Content-Type": []string{easyrpc.ContentTypeFor(false, kind)}}, Body: encodeMsg(in, kind)})
	if err != nil { return nil, err }
	if resp.Error != nil { return nil, resp.Error }
	out := &NoRouteResponse{}
	if err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }
	return out, nil
}

type AdminThingServiceService interface {
	Reset(ctx context.Context, in *NoRouteRequest) (*NoRouteResponse, error)
}

func RegisterAdminThingServiceService(impl AdminThingServiceService) *easyrpc.ServiceRegistry {
	reg := easyrpc.NewServiceRegistry()
	reg.Unary["Reset"] = func(ctx context.Context, req []byte) ([]byte, error) {
		in := &NoRouteRequest{}
		kind := easyrpc.HandlerContextFromContext(ctx).Kind
		if err := decodeMsg(req, in, kind); err != nil { return nil, err }
		out, err := impl.Reset(ctx, in)
		if err != nil { return nil, err }
		return encodeMsg(out, kind), nil
	}
	return reg
}

func protoBytes(m proto.Message) []byte {
	b, _ := proto.Marshal(m)
	return b
}

func encodeMsg(m proto.Message, kind easyrpc.ContentKind) []byte {
	if kind == easyrpc.KindJSON {
		b, err := protojson.Marshal(m)
		if err != nil {
			return []byte("{}")
		}
		return b
	}
	return protoBytes(m)
}

func decodeMsg(b []byte, m proto.Message, kind easyrpc.ContentKind) error {
	if kind == easyrpc.KindJSON {
		return protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(b, m)
	}
	return proto.Unmarshal(b, m)
}
