// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public final class ThingServiceClient {
  private let t: any Transport
  public init(_ t: any Transport) { self.t = t }
  public var lastTrailers: Headers = [:]
  public var lastStream: (any Stream)?

  public func getThing(req: Easyrpc_Kitchensink_V1_GetThingRequest, kind: String = "proto") async throws -> Easyrpc_Kitchensink_V1_GetThingResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/easyrpc.kitchensink.v1.ThingService/GetThing", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Easyrpc_Kitchensink_V1_GetThingResponse.self, kind)
  }

  public func listThings(req: Easyrpc_Kitchensink_V1_ListThingsRequest, kind: String = "proto") async throws -> Easyrpc_Kitchensink_V1_ListThingsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/easyrpc.kitchensink.v1.ThingService/ListThings", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Easyrpc_Kitchensink_V1_ListThingsResponse.self, kind)
  }

  public func watchThings(req: Easyrpc_Kitchensink_V1_WatchThingsRequest, kind: String = "proto") async throws -> AsyncThrowingStream<Easyrpc_Kitchensink_V1_WatchThingsResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "/easyrpc.kitchensink.v1.ThingService/WatchThings", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))
    self.lastStream = st
    while let msg = await st.recv() { cont.yield(try decodeMsg(msg, Easyrpc_Kitchensink_V1_WatchThingsResponse.self, kind)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func noRoute(req: Easyrpc_Kitchensink_V1_NoRouteRequest, kind: String = "proto") async throws -> Easyrpc_Kitchensink_V1_NoRouteResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/easyrpc.kitchensink.v1.ThingService/NoRoute", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Easyrpc_Kitchensink_V1_NoRouteResponse.self, kind)
  }

}