// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public final class AdminThingServiceClient {
  private let t: any Transport
  public init(_ t: any Transport) { self.t = t }
  public var lastTrailers: Headers = [:]
  public var lastStream: (any Stream)?

  public func reset(req: Easyrpc_Kitchensink_V1_NoRouteRequest, kind: String = "proto") async throws -> Easyrpc_Kitchensink_V1_NoRouteResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/easyrpc.kitchensink.v1.AdminThingService/Reset", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Easyrpc_Kitchensink_V1_NoRouteResponse.self, kind)
  }

}