// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.
import 'dart:typed_data';
import 'package:easy_rpc/easy_rpc.dart';
import 'package:easy_rpc/src/easyrpc/kitchensink/v1/kitchen.pb.dart' as m;

class AdminThingServiceClient {
  final Transport _t;
  AdminThingServiceClient(this._t);
  Request _req(String url, [Uint8List? body]) => Request(url: url, body: body);
  Headers lastTrailers = const {};
  RpcStream? lastStream;

  Future<m.NoRouteResponse> reset(m.NoRouteRequest req, {String kind = 'proto'}) async {
    final ct = contentTypeFor(false, kind);
    final res = await _t.send(Request(url: '/easyrpc.kitchensink.v1.AdminThingService/Reset', headers: {'content-type': [ct]}, body: Uint8List.fromList(encodeMsg(req, kind))));
    if (res.error != null) throw res.error!;
    lastTrailers = res.trailers;
    return decodeMsg<m.NoRouteResponse>(res.body!, () => m.NoRouteResponse(), kind);
  }

}