// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.
import 'dart:typed_data';
import 'package:easy_rpc/easy_rpc.dart';
import 'package:easy_rpc/src/easyrpc/kitchensink/v1/kitchen.pb.dart' as m;

class ThingServiceClient {
  final Transport _t;
  ThingServiceClient(this._t);
  Request _req(String url, [Uint8List? body]) => Request(url: url, body: body);
  Headers lastTrailers = const {};
  RpcStream? lastStream;

  Future<m.GetThingResponse> getThing(m.GetThingRequest req, {String kind = 'proto'}) async {
    final ct = contentTypeFor(false, kind);
    final res = await _t.send(Request(url: '/easyrpc.kitchensink.v1.ThingService/GetThing', headers: {'content-type': [ct]}, body: Uint8List.fromList(encodeMsg(req, kind))));
    if (res.error != null) throw res.error!;
    lastTrailers = res.trailers;
    return decodeMsg<m.GetThingResponse>(res.body!, () => m.GetThingResponse(), kind);
  }

  Future<m.ListThingsResponse> listThings(m.ListThingsRequest req, {String kind = 'proto'}) async {
    final ct = contentTypeFor(false, kind);
    final res = await _t.send(Request(url: '/easyrpc.kitchensink.v1.ThingService/ListThings', headers: {'content-type': [ct]}, body: Uint8List.fromList(encodeMsg(req, kind))));
    if (res.error != null) throw res.error!;
    lastTrailers = res.trailers;
    return decodeMsg<m.ListThingsResponse>(res.body!, () => m.ListThingsResponse(), kind);
  }

  Stream<m.WatchThingsResponse> watchThings(m.WatchThingsRequest req, {String kind = 'proto'}) async* {
    final ct = contentTypeFor(true, kind);
    final st = await _t.openStream(Request(url: '/easyrpc.kitchensink.v1.ThingService/WatchThings', headers: {'content-type': [ct]}, body: Uint8List.fromList(frame(encodeMsg(req, kind)))));
    lastStream = st;
    await for (final chunk in st.messages) { yield decodeMsg<m.WatchThingsResponse>(chunk, () => m.WatchThingsResponse(), kind); }
  }

  Future<m.NoRouteResponse> noRoute(m.NoRouteRequest req, {String kind = 'proto'}) async {
    final ct = contentTypeFor(false, kind);
    final res = await _t.send(Request(url: '/easyrpc.kitchensink.v1.ThingService/NoRoute', headers: {'content-type': [ct]}, body: Uint8List.fromList(encodeMsg(req, kind))));
    if (res.error != null) throw res.error!;
    lastTrailers = res.trailers;
    return decodeMsg<m.NoRouteResponse>(res.body!, () => m.NoRouteResponse(), kind);
  }

}