// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.
pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {
  vec![
  crate::protocol::MethodSpec { service: "easyrpc.kitchensink.v1.ThingService".to_string(), name: "GetThing".to_string(), path: "/easyrpc.kitchensink.v1.ThingService/GetThing".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.kitchensink.v1.ThingService".to_string(), name: "ListThings".to_string(), path: "/easyrpc.kitchensink.v1.ThingService/ListThings".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.kitchensink.v1.ThingService".to_string(), name: "WatchThings".to_string(), path: "/easyrpc.kitchensink.v1.ThingService/WatchThings".to_string(), client_stream: false, server_stream: true },
  crate::protocol::MethodSpec { service: "easyrpc.kitchensink.v1.ThingService".to_string(), name: "NoRoute".to_string(), path: "/easyrpc.kitchensink.v1.ThingService/NoRoute".to_string(), client_stream: false, server_stream: false },
  crate::protocol::MethodSpec { service: "easyrpc.kitchensink.v1.AdminThingService".to_string(), name: "Reset".to_string(), path: "/easyrpc.kitchensink.v1.AdminThingService/Reset".to_string(), client_stream: false, server_stream: false },
  ]
}
