// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package easyrpc

import easyrpc.*
import easyrpc.kitchensink.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class ThingServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun getThing(req: GetThingRequest, kind: String = KIND_PROTO): GetThingResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/easyrpc.kitchensink.v1.ThingService/GetThing", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, GetThingResponse.Companion, kind)
  }

  suspend fun listThings(req: ListThingsRequest, kind: String = KIND_PROTO): ListThingsResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/easyrpc.kitchensink.v1.ThingService/ListThings", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, ListThingsResponse.Companion, kind)
  }

  fun watchThings(req: WatchThingsRequest, kind: String = KIND_PROTO): Flow<WatchThingsResponse> = flow {
    val ct = contentTypeFor(true, kind)
    val st = t.openStream(Request(url = "/easyrpc.kitchensink.v1.ThingService/WatchThings", headers = mapOf("content-type" to listOf(ct)), body = frame(encodeMsg(req, kind))))
    while (true) { val p = st.recv() ?: break; emit(decodeMsg(p, WatchThingsResponse.Companion, kind)) }
    st.lastError()?.let { throw it }
  }

  suspend fun noRoute(req: NoRouteRequest, kind: String = KIND_PROTO): NoRouteResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/easyrpc.kitchensink.v1.ThingService/NoRoute", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, NoRouteResponse.Companion, kind)
  }

}