// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package easyrpc

import easyrpc.*
import easyrpc.kitchensink.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AdminThingServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun reset(req: NoRouteRequest, kind: String = KIND_PROTO): NoRouteResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/easyrpc.kitchensink.v1.AdminThingService/Reset", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, NoRouteResponse.Companion, kind)
  }

}