// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EasyRpc;
using Easyrpc.Kitchensink.V1;
using Google.Protobuf;

namespace EasyRpc {
  public class ThingServiceClient {
    public Dictionary<string, List<string>> LastTrailers { get; private set; } = new();
    private readonly Transport _t;
    public ThingServiceClient(Transport t) { _t = t; }

    public async Task<GetThingResponse> getThing(GetThingRequest req, string kind = "proto") {
      var ct = EasyRpc.Protocol.ContentTypeFor(false, kind);
      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };
      var res = await _t.Send(new Request { Url = "/easyrpc.kitchensink.v1.ThingService/GetThing", Headers = md, Body = EasyRpc.Protocol.EncodeMsg(req, kind) });
      LastTrailers = res.Trailers;
      if (res.Error != null) throw res.Error;
      return EasyRpc.Protocol.DecodeMsg<GetThingResponse>(res.Body, kind);
    }

    public async Task<ListThingsResponse> listThings(ListThingsRequest req, string kind = "proto") {
      var ct = EasyRpc.Protocol.ContentTypeFor(false, kind);
      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };
      var res = await _t.Send(new Request { Url = "/easyrpc.kitchensink.v1.ThingService/ListThings", Headers = md, Body = EasyRpc.Protocol.EncodeMsg(req, kind) });
      LastTrailers = res.Trailers;
      if (res.Error != null) throw res.Error;
      return EasyRpc.Protocol.DecodeMsg<ListThingsResponse>(res.Body, kind);
    }

    public async IAsyncEnumerable<WatchThingsResponse> watchThings(WatchThingsRequest req, string kind = "proto") {
      var ct = EasyRpc.Protocol.ContentTypeFor(true, kind);
      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };
      var stream = await _t.OpenStream(new Request { Url = "/easyrpc.kitchensink.v1.ThingService/WatchThings", Headers = md, Body = EasyRpc.Protocol.Frame(EasyRpc.Protocol.EncodeMsg(req, kind)) });
      await foreach (var m in stream) { yield return EasyRpc.Protocol.DecodeMsg<WatchThingsResponse>(m, kind); }
    }

    public async Task<NoRouteResponse> noRoute(NoRouteRequest req, string kind = "proto") {
      var ct = EasyRpc.Protocol.ContentTypeFor(false, kind);
      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };
      var res = await _t.Send(new Request { Url = "/easyrpc.kitchensink.v1.ThingService/NoRoute", Headers = md, Body = EasyRpc.Protocol.EncodeMsg(req, kind) });
      LastTrailers = res.Trailers;
      if (res.Error != null) throw res.Error;
      return EasyRpc.Protocol.DecodeMsg<NoRouteResponse>(res.Body, kind);
    }

  }
}