// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EasyRpc;
using Easyrpc.Kitchensink.V1;
using Google.Protobuf;

namespace EasyRpc {
  public class AdminThingServiceClient {
    public Dictionary<string, List<string>> LastTrailers { get; private set; } = new();
    private readonly Transport _t;
    public AdminThingServiceClient(Transport t) { _t = t; }

    public async Task<NoRouteResponse> reset(NoRouteRequest req, string kind = "proto") {
      var ct = EasyRpc.Protocol.ContentTypeFor(false, kind);
      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };
      var res = await _t.Send(new Request { Url = "/easyrpc.kitchensink.v1.AdminThingService/Reset", Headers = md, Body = EasyRpc.Protocol.EncodeMsg(req, kind) });
      LastTrailers = res.Trailers;
      if (res.Error != null) throw res.Error;
      return EasyRpc.Protocol.DecodeMsg<NoRouteResponse>(res.Body, kind);
    }

  }
}