# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for
import easyrpc.kitchensink.v1.kitchen_pb2 as m
import asyncio

class ThingServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def getThing(self, req: m.GetThingRequest, kind: str = "proto") -> m.GetThingResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.kitchensink.v1.ThingService/GetThing", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.GetThingResponse, kind)

    async def listThings(self, req: m.ListThingsRequest, kind: str = "proto") -> m.ListThingsResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.kitchensink.v1.ThingService/ListThings", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.ListThingsResponse, kind)

    async def watchThings(self, req: m.WatchThingsRequest, kind: str = "proto"):
        ct = content_type_for(True, kind)
        st = await self._t.open_stream(Request(url="/easyrpc.kitchensink.v1.ThingService/WatchThings", headers={"content-type": [ct]}, body=frame(encode_msg(req, kind))))
        return TypedStream(st, lambda b: decode_msg(b, m.WatchThingsResponse, kind))

    async def noRoute(self, req: m.NoRouteRequest, kind: str = "proto") -> m.NoRouteResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.kitchensink.v1.ThingService/NoRoute", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.NoRouteResponse, kind)
