# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.
from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for
import easyrpc.kitchensink.v1.kitchen_pb2 as m
import asyncio

class AdminThingServiceClient:
    def __init__(self, transport: Transport):
        self._t = transport
        self.last_trailers = {}

    async def reset(self, req: m.NoRouteRequest, kind: str = "proto") -> m.NoRouteResponse:
        ct = content_type_for(False, kind)
        res = await self._t.send(Request(url="/easyrpc.kitchensink.v1.AdminThingService/Reset", headers={"content-type": [ct]}, body=encode_msg(req, kind)))
        if res.error: raise res.error
        self.last_trailers = res.trailers
        return decode_msg(res.body, m.NoRouteResponse, kind)
