#!/usr/bin/env python3
"""protoc-gen-easyrpc-csharp renderer.

Emits `<file>[_<Service>]_easyrpc.cs` (one file per service). Config via `opt:`:

  ns=<namespace>       emitted C# namespace (default `EasyRpc`)
  msg_ns=<namespace>   namespace of the generated protobuf messages; defaults
                       to the proto `csharp_namespace` option, else the proto
                       package Pascal-cased (prefixed with `Easyrpc.`).
"""
from __future__ import annotations

from .core import camel, pascal


def render(file, methods, params):
    ns = params.get("ns", "EasyRpc")
    proto_pkg = file.package or "easyrpc"
    msg_ns = params.get("msg_ns")
    if msg_ns is None and file.HasField("options") and file.options.HasField("csharp_namespace"):
        msg_ns = file.options.csharp_namespace
    if msg_ns is None:
        msg_ns = ".".join(pascal(x) for x in proto_pkg.split(".") if x)
    if not msg_ns.startswith("Easyrpc"):
        msg_ns = "Easyrpc." + msg_ns

    base = file.name[:-6]
    svc_names = sorted({m.service.rsplit(".", 1)[-1] for m in methods})
    multi = len(svc_names) > 1
    out = []
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        client = svc_name + "Client"
        L = [
            "// Code generated by protoc-gen-easyrpc-csharp. DO NOT EDIT.",
            "using System;",
            "using System.Collections.Generic;",
            "using System.Threading.Tasks;",
            "using EasyRpc;",
            f"using {msg_ns};",
            "using Google.Protobuf;",
            "",
            f"namespace {ns} {{",
            f"  public class {client} {{",
            "    public Dictionary<string, List<string>> LastTrailers { get; private set; } = new();",
            "    private readonly Transport _t;",
            f"    public {client}(Transport t) {{ _t = t; }}",
            "",
        ]
        for m in smethods:
            if m.server_stream:
                L.append(f'    public async IAsyncEnumerable<{m.output}> {camel(m.name)}({m.input} req, string kind = "proto") {{')
                L.append('      var ct = EasyRpc.Protocol.ContentTypeFor(true, kind);')
                L.append('      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };')
                L.append(f'      var stream = await _t.OpenStream(new Request {{ Url = "{m.path}", Headers = md, Body = EasyRpc.Protocol.Frame(EasyRpc.Protocol.EncodeMsg(req, kind)) }});')
                L.append(f'      await foreach (var m in stream) {{ yield return EasyRpc.Protocol.DecodeMsg<{m.output}>(m, kind); }}')
                L.append("    }")
            else:
                L.append(f'    public async Task<{m.output}> {camel(m.name)}({m.input} req, string kind = "proto") {{')
                L.append('      var ct = EasyRpc.Protocol.ContentTypeFor(false, kind);')
                L.append('      var md = new Dictionary<string, List<string>> { ["content-type"] = new List<string> { ct } };')
                L.append(f'      var res = await _t.Send(new Request {{ Url = "{m.path}", Headers = md, Body = EasyRpc.Protocol.EncodeMsg(req, kind) }});')
                L.append("      LastTrailers = res.Trailers;")
                L.append("      if (res.Error != null) throw res.Error;")
                L.append(f"      return EasyRpc.Protocol.DecodeMsg<{m.output}>(res.Body, kind);")
                L.append("    }")
            L.append("")
        L.append("  }")
        L.append("}")
        suffix = ("_" + svc_name) if multi else ""
        out.append((base + suffix + "_easyrpc.cs", "\n".join(L)))
    return out
