#!/usr/bin/env python3
"""protoc-gen-easyrpc-dart renderer.

Emits `<file>[_<Service>]_easyrpc.dart` (one file per service). Config via
`opt:`:

  pb_root=<import root>   locates the generated `*_pb.dart` messages
                          (default `package:easy_rpc/src`).
"""
from __future__ import annotations

import os

from .core import camel


def render(file, methods, params):
    pb_root = params.get("pb_root", "package:easy_rpc/src")
    base = file.name[:-6]
    pkg_dir = os.path.dirname(file.name).replace("\\", "/")
    pb_import = f"{pb_root}/{pkg_dir}/{os.path.basename(base)}.pb.dart" if pkg_dir else f"{pb_root}/{os.path.basename(base)}.pb.dart"
    svc_names = sorted({m.service.rsplit(".", 1)[-1] for m in methods})
    multi = len(svc_names) > 1
    out = []
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        client = svc_name + "Client"
        L = [
            "// Code generated by protoc-gen-easyrpc-dart. DO NOT EDIT.",
            "import 'dart:typed_data';",
            "import 'package:easy_rpc/easy_rpc.dart';",
            f"import '{pb_import}' as m;",
            "",
            f"class {client} {{",
            "  final Transport _t;",
            f"  {client}(this._t);",
            "  Request _req(String url, [Uint8List? body]) => Request(url: url, body: body);",
            "  Headers lastTrailers = const {};",
            "  RpcStream? lastStream;",
            "",
        ]
        for m in smethods:
            if m.server_stream:
                L.append(f"  Stream<m.{m.output}> {camel(m.name)}(m.{m.input} req, {{String kind = 'proto'}}) async* {{")
                L.append("    final ct = contentTypeFor(true, kind);")
                L.append(f"    final st = await _t.openStream(Request(url: '{m.path}', headers: {{'content-type': [ct]}}, body: Uint8List.fromList(frame(encodeMsg(req, kind)))));")
                L.append("    lastStream = st;")
                L.append(f"    await for (final chunk in st.messages) {{ yield decodeMsg<m.{m.output}>(chunk, () => m.{m.output}(), kind); }}")
                L.append("  }")
            else:
                L.append(f"  Future<m.{m.output}> {camel(m.name)}(m.{m.input} req, {{String kind = 'proto'}}) async {{")
                L.append("    final ct = contentTypeFor(false, kind);")
                L.append(f"    final res = await _t.send(Request(url: '{m.path}', headers: {{'content-type': [ct]}}, body: Uint8List.fromList(encodeMsg(req, kind))));")
                L.append("    if (res.error != null) throw res.error!;")
                L.append("    lastTrailers = res.trailers;")
                L.append(f"    return decodeMsg<m.{m.output}>(res.body!, () => m.{m.output}(), kind);")
                L.append("  }")
            L.append("")
        L.append("}")
        suffix = ("_" + svc_name) if multi else ""
        out.append((base + suffix + "_easyrpc.dart", "\n".join(L)))
    return out
