#!/usr/bin/env python3
"""protoc-gen-easyrpc-go renderer.

Emits a single `<file>.easyrpc.go` per proto file: MethodSpecs, a strong-typed
Client, the Service interface and a Register helper, plus proto/protojson
encode/decode helpers. No `opt:` keys are consumed. Kept byte-identical to the
historical Go plugin.
"""
from __future__ import annotations

import json

from .core import last_type


def _go_str(s: str) -> str:
    """A Go double-quoted string literal. ASCII identifiers/paths only, where
    this is identical to Go's `%q` (strconv.Quote)."""
    return json.dumps(s)


def _sanitize_pkg(s: str) -> str:
    out = "".join(r for r in s if r.isascii() and (r.isalnum() or r == "_"))
    return out or "proto"


def _go_package_name(file) -> str:
    gp = file.options.go_package if (file.HasField("options") and file.options.HasField("go_package")) else ""
    if gp:
        if ";" in gp:
            return _sanitize_pkg(gp.rsplit(";", 1)[1])
        if "/" in gp:
            return _sanitize_pkg(gp.rsplit("/", 1)[1])
        return _sanitize_pkg(gp)
    pkg = file.package
    if "." in pkg:
        return _sanitize_pkg(pkg.rsplit(".", 1)[1])
    return _sanitize_pkg(pkg)


def render(file, methods, params):
    pkg = file.package
    buf: list[str] = []
    push = buf.append
    push("// Code generated by protoc-gen-easyrpc-go. DO NOT EDIT.")
    push("package " + _go_package_name(file) + "\n")
    push("import (")
    push('\teasyrpc "github.com/easy-utils/easy-rpc-go"')
    push('\t"context"')
    push('\t"google.golang.org/protobuf/encoding/protojson"')
    push('\t"google.golang.org/protobuf/proto"')
    push(")\n")

    svc_names = [s.name for s in file.service]
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        # Methods
        push(f"func {svc_name}_Methods() []easyrpc.MethodSpec {{")
        push("\treturn []easyrpc.MethodSpec{")
        for m in smethods:
            push(f'\t\t{{Service: {_go_str(m.service)}, Name: {_go_str(m.name)}, Path: {_go_str(m.path)}, ClientStream: false, ServerStream: {"true" if m.server_stream else "false"}}},')
        push("\t}")
        push("}\n")
        # Client
        push(f"type {svc_name}Client struct {{ rt easyrpc.Transport }}")
        push(f"func New{svc_name}Client(rt easyrpc.Transport) *{svc_name}Client {{ return &{svc_name}Client{{rt: rt}} }}\n")
        for m in smethods:
            if m.server_stream:
                push(f"func (c *{svc_name}Client) {m.name}(ctx context.Context, in *{m.input}, opts ...easyrpc.CallOption) (easyrpc.Stream, error) {{")
                push("\tkind := easyrpc.KindProto")
                push("\tfor _, o := range opts { o(&kind) }")
                push(f'\treturn c.rt.OpenStream(ctx, easyrpc.Request{{URL: {_go_str(m.path)}, Headers: easyrpc.Headers{{"Content-Type": []string{{easyrpc.ContentTypeFor(true, kind)}}}}, Body: easyrpc.Frame(encodeMsg(in, kind), false)}})')
                push("}\n")
            else:
                push(f"func (c *{svc_name}Client) {m.name}(ctx context.Context, in *{m.input}, opts ...easyrpc.CallOption) (*{m.output}, error) {{")
                push("\tkind := easyrpc.KindProto")
                push("\tfor _, o := range opts { o(&kind) }")
                push(f'\tresp, err := c.rt.Send(ctx, easyrpc.Request{{URL: {_go_str(m.path)}, Headers: easyrpc.Headers{{"Content-Type": []string{{easyrpc.ContentTypeFor(false, kind)}}}}, Body: encodeMsg(in, kind)}})')
                push("\tif err != nil { return nil, err }")
                push("\tif resp.Error != nil { return nil, resp.Error }")
                push(f"\tout := &{m.output}{{}}")
                push("\tif err := decodeMsg(resp.Body, out, kind); err != nil { return nil, err }")
                push("\treturn out, nil")
                push("}\n")
        # Service interface + Register.
        push(f"type {svc_name}Service interface {{")
        for m in smethods:
            if m.server_stream:
                push(f"\t{m.name}(ctx context.Context, in *{m.input}, emit func(*{m.output}) error) error")
            else:
                push(f"\t{m.name}(ctx context.Context, in *{m.input}) (*{m.output}, error)")
        push("}\n")
        push(f"func Register{svc_name}Service(impl {svc_name}Service) *easyrpc.ServiceRegistry {{")
        push("\treg := easyrpc.NewServiceRegistry()")
        for m in smethods:
            if m.server_stream:
                push(f'\treg.Stream[{_go_str(m.name)}] = func(ctx context.Context, req []byte, emit func([]byte, bool) error) error {{')
                push(f"\t\tin := &{m.input}{{}}")
                push("\t\tif err := decodeMsg(req, in, easyrpc.HandlerContextFromContext(ctx).Kind); err != nil { return err }")
                push("\t\tkind := easyrpc.HandlerContextFromContext(ctx).Kind")
                push(f"\t\treturn impl.{m.name}(ctx, in, func(out *{m.output}) error {{ return emit(encodeMsg(out, kind), false) }})")
                push("\t}")
            else:
                push(f'\treg.Unary[{_go_str(m.name)}] = func(ctx context.Context, req []byte) ([]byte, error) {{')
                push(f"\t\tin := &{m.input}{{}}")
                push("\t\tkind := easyrpc.HandlerContextFromContext(ctx).Kind")
                push("\t\tif err := decodeMsg(req, in, kind); err != nil { return nil, err }")
                push(f"\t\tout, err := impl.{m.name}(ctx, in)")
                push("\t\tif err != nil { return nil, err }")
                push("\t\treturn encodeMsg(out, kind), nil")
                push("\t}")
        push("\treturn reg")
        push("}\n")
    # helpers
    push("func protoBytes(m proto.Message) []byte {")
    push("\tb, _ := proto.Marshal(m)")
    push("\treturn b")
    push("}\n")
    push('func encodeMsg(m proto.Message, kind easyrpc.ContentKind) []byte {')
    push("\tif kind == easyrpc.KindJSON {")
    push("\t\tb, err := protojson.Marshal(m)")
    push("\t\tif err != nil {")
    push('\t\t\treturn []byte("{}")')
    push("\t\t}")
    push("\t\treturn b")
    push("\t}")
    push("\treturn protoBytes(m)")
    push("}\n")
    push("func decodeMsg(b []byte, m proto.Message, kind easyrpc.ContentKind) error {")
    push("\tif kind == easyrpc.KindJSON {")
    push("\t\treturn protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(b, m)")
    push("\t}")
    push("\treturn proto.Unmarshal(b, m)")
    push("}")
    base = file.name.removesuffix(".proto")
    return [(base + ".easyrpc.go", "\n".join(buf) + "\n")]
