#!/usr/bin/env python3
"""protoc-gen-easyrpc-kotlin renderer.

Emits `<file>[_<Service>]_easyrpc.kt` (one file per service). Kotlin
Multiplatform target: messages are generated by protoc-gen-pbandk into the
proto package; this plugin emits the client using pbandk encode/decode. Config
via `opt:`:

  pkg=<package>       emitted `package` for the client (default `easyrpc`)
  msg_pkg=<package>   package of the pbandk messages; defaults to the proto
                      `java_package` option, else the proto package.
"""
from __future__ import annotations

from .core import camel


def render(file, methods, params):
    out_pkg = params.get("pkg", "easyrpc")
    proto_pkg = file.package or "easyrpc"
    default_pkg = proto_pkg
    if file.HasField("options") and file.options.HasField("java_package"):
        default_pkg = file.options.java_package
    msg_pkg = params.get("msg_pkg") or default_pkg

    base = file.name[:-6]
    svc_names = sorted({m.service.rsplit(".", 1)[-1] for m in methods})
    multi = len(svc_names) > 1
    out = []
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        client = svc_name + "Client"
        L = [
            "// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.",
            f"package {out_pkg}", "", "import easyrpc.*",
            f"import {msg_pkg}.*",
            "import pbandk.decodeFromByteArray",
            "import pbandk.encodeToByteArray",
            "import kotlinx.coroutines.flow.Flow", "import kotlinx.coroutines.flow.flow", "",
            f"class {client}(private val t: Transport) {{",
            "  var lastTrailers: Map<String, List<String>> = emptyMap()",
        ]
        for m in smethods:
            if m.server_stream:
                L.append(f"  fun {camel(m.name)}(req: {m.input}, kind: String = KIND_PROTO): Flow<{m.output}> = flow {{")
                L.append("    val ct = contentTypeFor(true, kind)")
                L.append(f'    val st = t.openStream(Request(url = "{m.path}", headers = mapOf("content-type" to listOf(ct)), body = frame(encodeMsg(req, kind))))')
                L.append(f"    while (true) {{ val p = st.recv() ?: break; emit(decodeMsg(p, {m.output}.Companion, kind)) }}")
                L.append("    st.lastError()?.let { throw it }")
                L.append("  }")
            else:
                L.append(f"  suspend fun {camel(m.name)}(req: {m.input}, kind: String = KIND_PROTO): {m.output} {{")
                L.append("    val ct = contentTypeFor(false, kind)")
                L.append(f'    val res = t.send(Request(url = "{m.path}", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))')
                L.append("    res.error?.let{ throw it }")
                L.append("    lastTrailers = res.trailers")
                L.append(f"    return decodeMsg(res.body, {m.output}.Companion, kind)")
                L.append("  }")
            L.append("")
        L.append("}")
        suffix = ("_" + svc_name) if multi else ""
        out.append((base + suffix + "_easyrpc.kt", "\n".join(L)))
    return out
