#!/usr/bin/env python3
"""protoc-gen-easyrpc-python renderer.

Emits `<file>[_<Service>]_easyrpc_pb2.py` (one file per service) — a
strong-typed client wrapping the core Transport. Config via `opt:`:

  lib=<root>   cross-package library root for the generated client (default
               `easyrpc`); controls the message import path.
"""
from __future__ import annotations

import os

from .core import camel


def _message_module(file, lib: str) -> str:
    base = file.name[:-6]  # strip .proto
    pkg_dir = os.path.dirname(file.name).replace("\\", "/")
    parts = pkg_dir.split("/") if pkg_dir else []
    if parts and parts[0] == lib:
        parts = parts[1:]
    pkg_dir = "/".join(parts)
    pkg_dir = pkg_dir.replace(".", "_")
    mod_base = os.path.basename(base)
    if pkg_dir.split(".")[0] == lib:
        mod_path = f"{pkg_dir}/{mod_base}_pb2"
    else:
        mod_path = f"{lib}.{pkg_dir}/{mod_base}_pb2" if pkg_dir else f"{lib}.{mod_base}_pb2"
    return mod_path.replace("/", ".")


def render(file, methods, params):
    lib = params.get("lib", "easyrpc")
    base = file.name[:-6]
    mod_path = _message_module(file, lib)
    svc_names = sorted({m.service.rsplit(".", 1)[-1] for m in methods})
    multi = len(svc_names) > 1
    out = []
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        client = svc_name + "Client"
        L = [
            "# Code generated by protoc-gen-easyrpc-python. DO NOT EDIT.",
            "from easyrpc import Transport, Request, frame, TypedStream, encode_msg, decode_msg, content_type_for",
            f"import {mod_path} as m",
            "import asyncio", "",
            f"class {client}:",
            "    def __init__(self, transport: Transport):",
            "        self._t = transport",
            "        self.last_trailers = {}", "",
        ]
        for m in smethods:
            if m.server_stream:
                L.append(f'    async def {camel(m.name)}(self, req: m.{m.input}, kind: str = "proto"):')
                L.append("        ct = content_type_for(True, kind)")
                L.append(f'        st = await self._t.open_stream(Request(url="{m.path}", headers={{"content-type": [ct]}}, body=frame(encode_msg(req, kind))))')
                L.append(f"        return TypedStream(st, lambda b: decode_msg(b, m.{m.output}, kind))")
                L.append("")
            else:
                L.append(f'    async def {camel(m.name)}(self, req: m.{m.input}, kind: str = "proto") -> m.{m.output}:')
                L.append("        ct = content_type_for(False, kind)")
                L.append(f'        res = await self._t.send(Request(url="{m.path}", headers={{"content-type": [ct]}}, body=encode_msg(req, kind)))')
                L.append("        if res.error: raise res.error")
                L.append("        self.last_trailers = res.trailers")
                L.append(f"        return decode_msg(res.body, m.{m.output}, kind)")
                L.append("")
        suffix = ("_" + svc_name) if multi else ""
        out.append((base + suffix + "_easyrpc_pb2.py", "\n".join(L)))
    return out
