#!/usr/bin/env python3
"""protoc-gen-easyrpc-rust renderer.

Emits a single `<file>_easyrpc.rs` per proto file with a `method_specs()` table
referencing `crate::protocol::MethodSpec`. No `opt:` keys are consumed. Kept
byte-identical to the historical Rust plugin (Rust `{:?}` string escaping maps
to JSON string escaping for the ASCII identifiers/paths we emit).
"""
from __future__ import annotations

import json


def _rust_str(s: str) -> str:
    """A Rust `{:?}` debug string literal. For our values (ASCII identifiers and
    `/pkg.Service/Method` paths) this equals a JSON double-quoted literal."""
    return json.dumps(s)


def render(file, methods, params):
    out = []
    out.append("// Code generated by protoc-gen-easyrpc-rust. DO NOT EDIT.")
    out.append("pub fn method_specs() -> Vec<crate::protocol::MethodSpec> {")
    out.append("  vec![")
    for m in methods:
        out.append(
            "  crate::protocol::MethodSpec {{ service: {}.to_string(), name: {}.to_string(), path: {}.to_string(), client_stream: {}, server_stream: {} }},".format(
                _rust_str(m.service), _rust_str(m.name), _rust_str(m.path),
                "true" if m.client_stream else "false",
                "true" if m.server_stream else "false",
            )
        )
    out.append("  ]")
    out.append("}")
    base = file.name.removesuffix(".proto")
    return [(base + "_easyrpc.rs", "\n".join(out) + "\n")]
