#!/usr/bin/env python3
"""protoc-gen-easyrpc-swift renderer.

Emits `<file>[_<Service>]_easyrpc.swift` (one file per service). Config via
`opt:`:

  msg_prefix=<Prefix>   Swift protobuf type prefix (e.g. `Agent_V1`); defaults
                        to the Pascal-joined proto package segments.
"""
from __future__ import annotations

from .core import camel


def _default_prefix(pkg: str) -> str:
    parts = [x[:1].upper() + x[1:] for x in (pkg or "easyrpc").split(".") if x]
    return "_".join(parts)


def render(file, methods, params):
    pre = params.get("msg_prefix") or _default_prefix(file.package or "easyrpc")
    base = file.name[:-6]
    svc_names = sorted({m.service.rsplit(".", 1)[-1] for m in methods})
    multi = len(svc_names) > 1
    out = []
    for svc_name in svc_names:
        smethods = [m for m in methods if m.service.rsplit(".", 1)[-1] == svc_name]
        client = svc_name + "Client"
        L = [
            "// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.",
            "import easyRpc", "",
            f"public final class {client} {{",
            "  private let t: any Transport",
            f"  public init(_ t: any Transport) {{ self.t = t }}",
            "  public var lastTrailers: Headers = [:]",
            "  public var lastStream: (any Stream)?", "",
        ]
        for m in smethods:
            if m.server_stream:
                L.append(f'  public func {camel(m.name)}(req: {pre}_{m.input}, kind: String = "proto") async throws -> AsyncThrowingStream<{pre}_{m.output}, Error>')
                L.append(f'  {{ AsyncThrowingStream {{ cont in Task {{ do {{ let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "{m.path}", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))')
                L.append("    self.lastStream = st")
                L.append(f"    while let msg = await st.recv() {{ cont.yield(try decodeMsg(msg, {pre}_{m.output}.self, kind)) }}")
                L.append(f"    if let e = st.lastError() {{ throw e }}")
                L.append("    cont.finish() } catch { cont.finish(throwing: error) } } } }")
            else:
                L.append(f'  public func {camel(m.name)}(req: {pre}_{m.input}, kind: String = "proto") async throws -> {pre}_{m.output} {{')
                L.append("    let ct = contentTypeFor(false, kind)")
                L.append(f'    let res = try await t.send(Request(url: "{m.path}", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))')
                L.append("    self.lastTrailers = res.trailers")
                L.append(f"    if let e = res.error {{ throw e }}")
                L.append(f"    return try decodeMsg(res.body, {pre}_{m.output}.self, kind)")
                L.append("  }")
            L.append("")
        L.append("}")
        suffix = ("_" + svc_name) if multi else ""
        out.append((base + suffix + "_easyrpc.swift", "\n".join(L)))
    return out
