#!/usr/bin/env python3
"""protoc-gen-easyrpc-ts renderer.

Emits a single `<file>_easyrpc.ts` per proto file: methodSpecs, per-service
client factories, ServiceImpl interfaces and server Handler maps. No `opt:`
keys are consumed (the generated code is self-describing). Kept byte-identical
to the historical TypeScript plugin.
"""
from __future__ import annotations

import json


def _js_str(s: str) -> str:
    """JSON string literal — identical to JS `JSON.stringify` for our values."""
    return json.dumps(s, ensure_ascii=False)


def _last_type(t: str) -> str:
    return t.rsplit(".", 1)[-1] if t else ""


def _base_name(file) -> str:
    return file.name.rsplit("/", 1)[-1].removesuffix(".proto")


def _collect_file_descs(file) -> list[str]:
    n = file.name.removesuffix(".proto").split("/")[-1]
    return ["file_" + "_".join(list(file.package.split(".")) + [n])]


def _collect_msg_names(file) -> list[str]:
    seen: dict[str, None] = {}
    for svc in file.service:
        for m in svc.method:
            seen.setdefault(_last_type(m.input_type), None)
            seen.setdefault(_last_type(m.output_type), None)
    return list(seen)


def _services(file, methods):
    out = []
    for svc in file.service:
        svc_name = svc.name or ""
        lst = []
        for m in svc.method:
            meta = next((x for x in methods if x.name == (m.name or "")
                         and x.service.endswith(svc_name)), None)
            lst.append({
                "name": m.name or "",
                "inMsg": _last_type(m.input_type),
                "outMsg": _last_type(m.output_type),
                "serverStream": m.server_streaming is True,
                "path": meta.path if meta else f"/{m.name}",
            })
        out.append({"name": svc_name, "methods": lst})
    return out


def _camel(s: str) -> str:
    return s[:1].lower() + s[1:] if s else ""


def render(file, methods, params):
    services = _services(file, methods)
    base = file.name.removesuffix(".proto")
    lines: list[str] = []
    push = lines.append
    push("// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.")
    push("import { create, fromBinary, toBinary, fromJson, toJson, createRegistry } from '@bufbuild/protobuf'")
    push("import type { DescMessage } from '@bufbuild/protobuf'")
    push("import type { MessageInitShape } from '@bufbuild/protobuf'")
    push("import type { Transport, MethodSpec, Headers, HandlerContext, ServerStream } from '../../../protocol.js'")
    push("import { frame, contentKindHeader } from '../../../protocol.js'")
    push("import type { ContentKind } from '../../../protocol.js'")
    push("import type { ServiceHandlers } from '../../../protocol.js'")
    push("")
    push("/** Per-call options: cancellation, extra metadata, and unary trailer hook. */")
    push("export interface CallOptions { signal?: AbortSignal; metadata?: Headers; onTrailer?: (trailers: Headers) => void; kind?: ContentKind }")
    file_descs = _collect_file_descs(file)
    if file_descs:
        push(f"import {{ {', '.join(file_descs)} }} from './{_base_name(file)}_pb.js'")
    push("")
    push("/** JSON type registry (required to encode google.protobuf.Any to JSON). */")
    push(f"const jsonRegistry = createRegistry({', '.join(file_descs)})")
    push("const toJsonOpts = { registry: jsonRegistry }")
    msg_names = _collect_msg_names(file)
    if msg_names:
        schema_names = ", ".join(n + "Schema" for n in msg_names)
        push(f"import {{ {', '.join(msg_names)}, {schema_names} }} from './{_base_name(file)}_pb.js'")
    push("")
    push("export const methodSpecs: MethodSpec[] = [")
    for m in methods:
        push(f"  {{ service: {_js_str(m.service)}, name: {_js_str(m.name)}, path: {_js_str(m.path)}, clientStream: {'true' if m.client_stream else 'false'}, serverStream: {'true' if m.server_stream else 'false'} }},")
    push("]")
    push("")

    for svc in services:
        iface = f"{svc['name']}Client"
        client_name = f"create{svc['name']}Client"
        push(f"export interface {iface} {{")
        for m in svc["methods"]:
            ret = f"Promise<ServerStream<{m['outMsg']}>>" if m["serverStream"] else f"Promise<{m['outMsg']}>"
            push(f"  {_camel(m['name'])}(req: MessageInitShape<typeof {m['inMsg']}Schema>, options?: CallOptions): {ret}")
        push("}")
        push(f"export function {client_name}(transport: Transport): {iface} {{")
        push("  return {")
        for m in svc["methods"]:
            stream = m["serverStream"]
            push(f"    async {_camel(m['name'])}(reqInit, options = {{}}) {{")
            push(f"      const req = create({m['inMsg']}Schema, reqInit)")
            push("      const kind: ContentKind = options.kind ?? 'proto'")
            push(f"      const ct = contentKindHeader({'true' if stream else 'false'}, kind)")
            push("      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }")
            push(f"      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson({m['inMsg']}Schema, req, toJsonOpts))) : toBinary({m['inMsg']}Schema, req)")
            if stream:
                push("      const body = frame(encode())")
            else:
                push("      const body = encode()")
            push(f"      const call = {{ url: {_js_str(m['path'])}, headers: md, body, ...(options.signal !== undefined ? {{ signal: options.signal }} : {{}}) }}")
            if stream:
                push("      const s = await transport.openStream(call)")
                push(f"      const decode = (chunk: Uint8Array) => kind === 'json' ? fromJson({m['outMsg']}Schema, JSON.parse(new TextDecoder().decode(chunk))) : fromBinary({m['outMsg']}Schema, chunk)")
                push(f"      const out: ServerStream<{m['outMsg']}> = {{")
                push("        async *[Symbol.asyncIterator]() { for await (const chunk of s) yield decode(chunk) },")
                push("        trailers: () => s.trailers(),")
                push("        cancel: () => s.cancel(),")
                push("      }")
                push("      return out")
            else:
                push("      const res = await transport.send(call)")
                push("      if (res.error) throw res.error")
                push("      options.onTrailer?.(res.trailers ?? {})")
                push(f"      return kind === 'json' ? fromJson({m['outMsg']}Schema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary({m['outMsg']}Schema, res.body)")
            push("    },")
        push("  }")
        push("}")
        push("")
        push(f"export interface {svc['name']}ServiceImpl {{")
        for m in svc["methods"]:
            ret = f"AsyncIterable<MessageInitShape<typeof {m['outMsg']}Schema>>" if m["serverStream"] else f"Promise<MessageInitShape<typeof {m['outMsg']}Schema>>"
            push(f"  {_camel(m['name'])}(req: {m['inMsg']}, ctx: HandlerContext): {ret}")
        push("}")
        push("")
        push(f"export function {svc['name']}Handlers(impl: {svc['name']}ServiceImpl): ServiceHandlers {{")
        push("  const unary: ServiceHandlers['unary'] = {}")
        push("  const stream: ServiceHandlers['stream'] = {}")
        for m in svc["methods"]:
            if m["serverStream"]:
                push(f"  stream[{_js_str(m['name'])}] = async (input, ctx, emit) => {{")
                push(f"    const req = ctx.kind === 'json' ? fromJson({m['inMsg']}Schema, JSON.parse(new TextDecoder().decode(input))) : fromBinary({m['inMsg']}Schema, input)")
                push(f"    const enc = (v: MessageInitShape<typeof {m['outMsg']}Schema>) => {{ const msg = create({m['outMsg']}Schema, v); return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson({m['outMsg']}Schema, msg, toJsonOpts))) : toBinary({m['outMsg']}Schema, msg) }}")
                push(f"    for await (const v of await impl.{_camel(m['name'])}(req, ctx)) {{ await emit(enc(v), false) }}")
                push("    await emit(new Uint8Array(0), true)")
                push("  }")
            else:
                push(f"  unary[{_js_str(m['name'])}] = async (input, ctx) => {{")
                push(f"    const req = ctx.kind === 'json' ? fromJson({m['inMsg']}Schema, JSON.parse(new TextDecoder().decode(input))) : fromBinary({m['inMsg']}Schema, input)")
                push(f"    const v = create({m['outMsg']}Schema, await impl.{_camel(m['name'])}(req, ctx))")
                push(f"    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson({m['outMsg']}Schema, v, toJsonOpts))) : toBinary({m['outMsg']}Schema, v)")
                push("  }")
        push("  return { unary, stream }")
        push("}")
        push("")
    return [(base + "_easyrpc.ts", "\n".join(lines) + "\n")]
